spring:
  application:
    name: youthcon-2024
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always
      platform: h2

logging:
  level:
    org:
      springframework:
        orm:
          jpa: debug
        transaction:
          interceptor: trace